### ISSUE TITLE
MAC platform = ststm8 build    error: 'long float' is invalid

### ISSUE THREAD

**Issue by hzhh110** [platformio/platform-ststm8#15]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:168:1: error: 'long float' is invalid

**Comment by postpersonality** [comment]
https://community.platformio.org/t/begginer-in-platform-io-need-help-with-programming-stm8/9078/4

The solution is to use main.c instead of main.cpp

**Comment by valeros** [comment]
Sduino doesn't support C++ sources. Please use `.c` extension for source files.
