### ISSUE TITLE
Compile error on Windows and Linux, only normal compile on MAC, but there are still problems

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [platformio/platform-ststm8#17]
version: Core 4.3.3·Home 3.2.2

question: There was a compilation error on Windows and Linux, and even with clang installed, the compilation failed~~

expect: Can be used on Windows and Linux~~

**Comment by Conmi-WhiteJoker** [comment]
![image](https://user-images.githubusercontent.com/39817817/81905496-5d1f1400-95f7-11ea-8b7b-136629a9e3db.png)

**Comment by cednik** [comment]
I found the same problem, triing to compile new empty project.
PIO Core 4.3.3 on VSCode, Win10x64.
After renaming main.cpp to main.c and remove warnings form HardwareSerial.c, weak_atexit.c and WInterrupts.c, I stucked on Error 309, described in Issue #12.

**Comment by Conmi-WhiteJoker** [comment]
Thank you for your help,cednik.
