### ISSUE TITLE
Hello, community maintainers, how do you use a watchdog in an Arduino IDE？

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [platformio/platform-ststm8#19]
I don't know if I can use "IWDG" directly, or if there is a better encapsulation in the existing framework, but I haven't found it yet.
Thanks！
~

**Comment by valeros** [comment]
Hi @Conmi-WhiteJoker ! Please forward your question to the proper repository https://github.com/tenbaht/sduino
