### ISSUE TITLE
Hello, community maintainers,how do you use "noInterrupts()" in an Arduino IDE？

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [platformio/platform-ststm8#20]
ArduinoIDE error msg:
?ASlink-Warning-Undefined Global '_cli' referenced by module 'STM8S105K4T6_ino'

**Comment by valeros** [comment]
Hi @Conmi-WhiteJoker ! Please forward your question to proper repository https://github.com/tenbaht/sduino
