### ISSUE TITLE
Erreurs #include détectées. Mettez à jour includePath. Les tildes sont désactivés pour cette unité de traduction

### ISSUE THREAD

**Issue by ipa64** [platformio/platform-ststm8#26]
Hi, 
vscode on mac version 1.50.1 
platform = ststm8
board = stm8sblue

I get this error in the editor, for most of #include lines. 
But I can build the project without any issue.
To solve it I had to edit setting.json to add this input :

{
    "C_Cpp.default.systemIncludePath": ["/Users/iPa64/.platformio/packages/toolchain-sdcc/share/sdcc/include/"]
}

**Comment by maxgerhardt** [comment]
VSCode cannot handle SDCC as the compiler, only Microsoft ones, GCC derivatives and clang. This is expected.
