### ISSUE TITLE
There is a error 309 when it's building

### ISSUE THREAD

**Issue by edgexie** [platformio/platform-ststm8#32]
There is a error 309 when it's building
![image](https://user-images.githubusercontent.com/18474752/108439621-9a05ee80-728c-11eb-9770-3e30494c92ab.png)

system: windows10-64bit
platformio core: 5.1.0
platformio home: 3.3.3

I find some community with this issue, and I update SDCC version to 4.x , it can be build success.

[reference](https://community.platformio.org/t/error-309-arduino-fade-all-pins-for-the-platform-st-stm8/13690/12)

**Comment by valeros** [comment]
Duplicate https://github.com/platformio/platform-ststm8/issues/12
