### ISSUE TITLE
Please add support for Nucleo-8S208RB board

### ISSUE THREAD

**Issue by gicking** [platformio/platform-ststm8#33]
please consider adding support for the Nucleo-8S208RB development board by STM. Thanks a lot in advance!

https://www.st.com/en/evaluation-tools/nucleo-8s208rb.html

**Comment by maxgerhardt** [comment]
Hey, do you also have a board to test? 

Please again execute the steps at #34 but with the modifications to
2. Create a new file `nucleo_8s208rb.json` in `boards/`
3. Fill it with the content 
```json
{
    "build": {
      "core": "sduino",
      "extra_flags": "-DSTM8S_208RB -DSTM8S208",
      "f_cpu": "16000000L",
      "cpu": "stm8",
      "mcu": "stm8s208rbt6",
      "variant": "mb208"
    }, 
    "frameworks": [
      "arduino",
      "spl"
    ],
    "upload": {
      "maximum_ram_size": 6144,
      "maximum_size": 131072,
      "protocol": "stlinkv2",
      "protocols": [
        "stlinkv2",
        "serial"
      ]
    },
    "name": "NUCLEO-8S208RB",
    "url": "https://www.st.com/en/evaluation-tools/nucleo-8s208rb.html",
    "vendor": "STMicroelectronics"
  }
```
4. `platformio.ini` 
```
[env:nucleo_8s208rb]
platform = ststm8
board = nucleo_8s208rb
framework = spl
; no upload_command needed, automatically derives -p stm8s208?b which is correct
```
(may also be added to the existing `platformio.ini`, but then make sure to [use the project and environment switcher](https://docs.platformio.org/en/latest/integration/ide/vscode.html#project-tasks) to get the right environment)

The rest is the same (e.g. regarding the LED on pin PC5). Try to compile and uplaod and see if that works :)
