### ISSUE TITLE
please update SDCC compiler

### ISSUE THREAD

**Issue by gicking** [platformio/platform-ststm8#36]
The SDCC compiler used for STM is v3.8.4. Please consider updating to the most recent version. 

SDCC is available from http://sdcc.sourceforge.net/

 ```
 - framework-arduinoststm8 0.40.181216 
 - tool-stm8binutils 0.230.0 (2.30) 
 - toolchain-sdcc 1.30804.10766 (3.8.4)

```

**Comment by maxgerhardt** [comment]
Duplicate of https://github.com/platformio/platform-ststm8/issues/13

**Comment by gicking** [comment]
close, because duplicate of #13
