### ISSUE TITLE
SDCC 4.1.0 package not available for 32-bit Windows

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-ststm8#50]
Per https://community.platformio.org/t/can-not-install-stm8-2-0-0-platform/23220.

>PIO Core Call Error: “Platform Manager: Installing ststm8\r\nPlatform Manager: ststm8 @ 2.0.0 has been installed!\r\nTool Manager: Installing platformio/toolchain-sdcc @ ~1.40100.0\r\n\n\nError: Could not find the package with ‘platformio/toolchain-sdcc @ ~1.40100.0’ requirements for your system ‘windows_x86’”

**Comment by Vittaly** [comment]
I made pool request to fix problem with incorrect OS version https://github.com/platformio/platformio-core/pull/4134/files
