### ISSUE TITLE
Build issues of example

### ISSUE THREAD

**Issue by rocketstrong600** [platformio/platform-ststm8#8]
`PS C:\Users\12102376\Documents\PlatformIO\Projects\190328-172626-arduino-fade-all-pins> pio run
Processing stm8sblue (platform: ststm8; board: stm8sblue; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm8/stm8sblue.html
PLATFORM: ST STM8 > ST STM8S103F3 Breakout Board
HARDWARE: STM8S103F3P6 16MHz 1KB RAM (8KB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 12 compatible libraries
Scanning dependencies...
No dependencies
Archiving .pioenvs\stm8sblue\libFrameworkArduinoVariant.lib
Compiling .pioenvs\stm8sblue\FrameworkArduino\weak_serialEvent.c.rel
Compiling .pioenvs\stm8sblue\FrameworkArduino\wiring.c.rel
Compiling .pioenvs\stm8sblue\FrameworkArduino\wiring_analog.c.rel*** [.pioenvs\stm8sblue\libFrameworkArduinoVariant.lib] Error 309

================================================================ [ERROR] Took 0.87 seconds ================================================================
PS C:\Users\12102376\Documents\PlatformIO\Projects\190328-172626-arduino-fade-all-pins>`

**Comment by ivankravets** [comment]
Please provide your `platformio.ini`.

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by ElliotCui97** [comment]
[env:stm8sblue]
platform = ststm8
board = stm8sblue
framework = arduino

**Comment by ElliotCui97** [comment]
I have the same problem.

**Comment by ElliotCui97** [comment]
> Executing task in folder STM8_LED_TEST: C:\Users\zjcui\.platformio\penv\Scripts\platformio.exe run --environment stm8sblue <

Processing stm8sblue (platform: ststm8; board: stm8sblue; framework: arduino)
-----------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm8/stm8sblue.html
PLATFORM: ST STM8 > ST STM8S103F3 Breakout Board
HARDWARE: STM8S103F3P6 16MHz 1KB RAM (8KB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 12 compatible libraries
Scanning dependencies...
No dependencies
Compiling .pioenvs\stm8sblue\src\main.c.rel
Archiving .pioenvs\stm8sblue\libFrameworkArduinoVariant.lib
Compiling .pioenvs\stm8sblue\FrameworkArduino\HardwareSerial.c.rel
Compiling .pioenvs\stm8sblue\FrameworkArduino\Print-float.c.rel
*** [.pioenvs\stm8sblue\libFrameworkArduinoVariant.lib] Error 309
C:\Users\zjcui\.platformio\packages\framework-arduinoststm8\cores\sduino\HardwareSerial.c:38:2: warning: #warning
"using uart1 for HardwareSerial"

**Comment by xfdr0805** [comment]
I have the same problem on win10 x64

Processing stm8sblue (platform: ststm8; board: stm8sblue; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm8/stm8sblue.html
PLATFORM: ST STM8 > ST STM8S103F3 Breakout Board
HARDWARE: STM8S103F3P6 16MHz 1KB RAM (8KB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 15 compatible libraries
Scanning dependencies...
No dependencies
Archiving .pioenvs\stm8sblue\libFrameworkArduinoVariant.lib
Compiling .pioenvs\stm8sblue\FrameworkArduino\weak_atexit.c.rel
Compiling .pioenvs\stm8sblue\FrameworkArduino\weak_initVariant.c.rel
Compiling .pioenvs\stm8sblue\FrameworkArduino\weak_serialEvent.c.rel
Compiling .pioenvs\stm8sblue\FrameworkArduino\wiring.c.rel
Compiling .pioenvs\stm8sblue\FrameworkArduino\wiring_analog.c.rel
Compiling .pioenvs\stm8sblue\FrameworkArduino\wiring_digital.c.rel
*** [.pioenvs\stm8sblue\libFrameworkArduinoVariant.lib] Error 309Compiling .pioenvs\stm8sblue\FrameworkArduino\wiring_pulse.c.rel

C:\users\xfdr0\.platformio\packages\framework-arduinoststm8\cores\sduino\weak_atexit.c:13: warning 85: in function atexit unreferenced function argument : 'func'
C:/users/xfdr0/.platformio/packages/framework-arduinoststm8/variants/standard/pins_arduino.h:260: warning 158: overflow in implicit constant conversion
